### ISSUE TITLE
reservedns parameter fails to deploy vms

### ISSUE THREAD

**Issue by gmontalvoy** [karmab/kcli#104]
Hi all,

I'm trying to use kcli to deploy vms using a plan that includes the following 

```
[...]
master01.local:
  template: rhel-server-7.5-x86_64-kvm.qcow2
  numcpus: 2
  memory: 4086
  reservedns: true
  domain: labs.local
  dns: labs.local
  nets:
    - pubnet
    - privnet
  disks:
    - size: 10
    - size: 10
  pool: default
  scripts:
    - register.sh
[...]
```

If you try to deploy a new server using a plan like that it will raise the following error:
```
Using trusting_rosalind as name of the plan
Deploying Networks...
Network privnet skipped!
Network pubnet skipped!
Deploying Templates...
Template rhel-server-7.5-x86_64-kvm.qcow2 skipped!
Deploying Vms...
Waiting 5 seconds to grab ip and create DNS record...
Waiting 5 seconds to grab ip and create DNS record...
Waiting 5 seconds to grab ip and create DNS record...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==12.1', 'console_scripts', 'kcli')()
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 1238, in cli
    args.func(args)
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 649, in plan
    overrides=overrides, info=info)
  File "/usr/lib/python3.6/site-packages/kvirt/config.py", line 1053, in plan
    files=files, enableroot=enableroot, overrides=overrides, tags=tags)
  File "/usr/lib/python3.6/site-packages/kvirt/kvm/__init__.py", line 431, in create
    self.reserve_dns(name, nets=nets, domain=domain, alias=alias)
  File "/usr/lib/python3.6/site-packages/kvirt/kvm/__init__.py", line 1101, in reserve_dns
    conn.networkDefineXML(newxml)
  File "/usr/lib64/python3.6/site-packages/libvirt.py", line 4154, in networkDefineXML
    ret = libvirtmod.virNetworkDefineXML(self._o, xml)
TypeError: virNetworkDefineXML() argument 2 must be str or None, not bytes
```

**Comment by karmab** [comment]
hello,
may i ask version sir ?

**Comment by gmontalvoy** [comment]
Hi,

Sure, kcli=12.1

**Comment by karmab** [comment]
should be fixed with https://github.com/karmab/kcli/commit/45b0d6914c49a18cc6909d9699676f4501caf81e

**Comment by gmontalvoy** [comment]
Confirmed, thank you!
