### ISSUE TITLE
Error joining machine by ssh

### ISSUE THREAD

**Issue by jparrill** [karmab/kcli#165]
- **Plan**: openshift4
- **Kcli version**: (pip3)
```
[root@qct-d14u09 ~]# kcli --version
20.2
```

- **Error**:
```
[root@qct-d14u09 ~]# kcli ssh openshift-installer
Traceback (most recent call last):
  File "/root/.local/bin/kcli", line 11, in <module>
    load_entry_point('kcli==20.2', 'console_scripts', 'kcli')()
  File "/root/.local/lib/python3.6/site-packages/kvirt/cli.py", line 2413, in cli
    args.func(args)
  File "/root/.local/lib/python3.6/site-packages/kvirt/cli.py", line 1255, in ssh_vm
    sshcommand = k.ssh(name, user=user, local=l, remote=r, tunnel=tunnel, insecure=insecure, cmd=cmd, X=X, Y=Y, D=D)
  File "/root/.local/lib/python3.6/site-packages/kvirt/kvm/__init__.py", line 2394, in ssh
    u, ip = self._ssh_credentials(name)
  File "/root/.local/lib/python3.6/site-packages/kvirt/kvm/__init__.py", line 2369, in _ssh_credentials
    for match in matches[0]:
TypeError: 'NoneType' object is not iterable

```

**Comment by karmab** [comment]
i think it was addressed in https://github.com/karmab/kcli/commit/29ef5d1438172d46e48bfdeacc77946459570949
