### ISSUE TITLE
pyyaml version should be >= 4.1

### ISSUE THREAD

**Issue by challs** [karmab/kcli#175]
With PyYaml version 3.13 (the version in Debian stable), I get the following traceback:

```
% kcli create host kvm -H kvm1 
Traceback (most recent call last):
  File "/home/chris/.local/bin/kcli", line 10, in <module>
    sys.exit(cli())
  File "/home/chris/.local/lib/python3.7/site-packages/kvirt/cli.py", line 2482, in cli
    args.func(args)
  File "/home/chris/.local/lib/python3.7/site-packages/kvirt/cli.py", line 1399, in create_host_kvm
    common.create_host(data)
  File "/home/chris/.local/lib/python3.7/site-packages/kvirt/common/__init__.py", line 1089, in create_host
    yaml.safe_dump(ini, conf_file, default_flow_style=False, encoding='utf-8', allow_unicode=True, sort_keys=False)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

It turns out that `sort_keys` was not introduced in PyYaml until [version 4.1](https://github.com/yaml/pyyaml/pull/143/commits/6aeacf096c496756a5939cc632fe4e71c61212d0).

Upgrading PyYaml using `pip3 install --upgrade pyyaml` worked around the problem.

**Comment by karmab** [comment]
Thanks for reporting this.
I knew it was risky to use this extra keyword and was too optimistic about its support on specific distributions (the yaml version in fedora's package for instance is high enough for this to work).
Let me think what the best approach is to handle this.

**Comment by karmab** [comment]
(ugly) fix at https://github.com/karmab/kcli/commit/581f02f97a21993024b7cfb5fb79b23328ae3b26
