### ISSUE TITLE
[ISSUE]Volumes option in containers is not working

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#24]
# When the container has no volumes:

`

 kcli plan -f test2.yml 
Using local hypervisor as no kcli.yml was found...
Deploying Containers...
Container centos deployed!
Traceback (most recent call last):
  File "/usr/bin/kcli", line 9, in <module>
    load_entry_point('kcli==4.2', 'console_scripts', 'kcli')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 838, in plan
    k.create_container(name=container, image=image, nets=nets, cmd=cmd, ports=ports, volumes=volumes, label=label)
  File "/usr/lib/python2.7/site-packages/kvirt/__init__.py", line 1546, in create_container
    for i, volume in enumerate(volumes):
TypeError: 'NoneType' object is not iterable

jtudelag @ jtudelag-t460s in ~/RedHat/POCs/fluentd [9:09:10] C:1
$ cat test2.yml 
centos:
  type: container
  image: centos
  cmd: /bin/bash
  ports:
   - 5500

jtudelag @ jtudelag-t460s in ~/RedHat/POCs/fluentd [9:12:49] 
$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-4.gitf499e8b.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      f499e8b/1.12.6
 Built:           Fri Jan 13 11:03:22 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-4.gitf499e8b.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      f499e8b/1.12.6
 Built:           Fri Jan 13 11:03:22 2017
 OS/Arch:         linux/amd64

jtudelag @ jtudelag-t460s in ~/RedHat/POCs/fluentd [9:13:02] C:2
$ kcli --version
kcli, version 4.2`

# When the container has volumes:

sudo kcli plan -f test2.yml
[sudo] password for jtudelag: 
Using local hypervisor as no kcli.yml was found...
Deploying Containers...
Container centos deployed!
Traceback (most recent call last):
  File "/bin/kcli", line 9, in <module>
    load_entry_point('kcli==4.2', 'console_scripts', 'kcli')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 838, in plan
    k.create_container(name=container, image=image, nets=nets, cmd=cmd, ports=ports, volumes=volumes, label=label)
  File "/usr/lib/python2.7/site-packages/kvirt/__init__.py", line 1575, in create_container
    d.containers.run(image, name=name, command=cmd, detach=True, ports=ports, volumes=volumes, stdin_open=True, tty=True, labels=labels)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 653, in run
    detach=detach, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 696, in create
    create_kwargs = _create_container_args(kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 882, in _create_container_args
    create_kwargs['volumes'] = [v.split(':')[0] for v in binds]
AttributeError: 'dict' object has no attribute 'split'

jtudelag @ jtudelag-t460s in ~/RedHat/POCs/fluentd [9:18:01] C:1
$ cat test2.yml 
centos:
  type: container
  image: centos
  cmd: /bin/bash
  ports:
   - 5500
  volumes:
   - /tmp/test

**Comment by karmab** [comment]
i believe this is fixed in latest commit https://github.com/karmab/kcli/commit/243ad523dfadaa62bf6b262261abac0f2a615024
