### ISSUE TITLE
Cleanup empty folders after a kcli command with the -u parameter ends with an error

### ISSUE THREAD

**Issue by ptrnull** [karmab/kcli#330]
When a user produces a failure in the kcli command, sometimes there is an empty folder left in the same folder that the kcli command was executed, for example:

```
$ kcli create plan -u kcli_plan_exam.yml -P student=candidate -P k8s=true
Using prickly-korsani as name of the plan
Retrieving specified plan from kcli_plan_exam.yml to prickly-korsani
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 4247, in cli
    args.func(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1736, in create_plan
    config.plan(plan, ansible=ansible, url=url, path=path, container=container, inputfile=inputfile,
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 1404, in plan
    common.fetch(url, path)
  File "/usr/lib/python3.9/site-packages/kvirt/common/__init__.py", line 73, in fetch
    urlretrieve(url, "%s/%s" % (path, shortname))
  File "/usr/lib64/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 501, in open
    req = Request(fullurl, data)
  File "/usr/lib64/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/usr/lib64/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/usr/lib64/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'kcli_plan_exam.yml'
```

The -u parameter was wrongly used in this example (should be an URL and was a local file, for a local file it should have been a -f flag), an empty folder called prickly-korsani was left after the command failed:
```
$ ls
hungry-jones  jovial-matoub  kcli_plan_exam.yml  prickly-korsani  readme.md
```

Some actions that can improve the behavior of the program:

- The error should be captured by the code to inform the user in a cleaner way instead of showing the full stack.
- In case of error, the created folder should be removed.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli#:~:text=karmab-,reject%20malformed%20url%20with%20create/download/update%20plan,-797a333
