### ISSUE TITLE
kcli clone fails

### ISSUE THREAD

**Issue by dgibson** [karmab/kcli#369]
When I attempt to clone a newly created VM with `kcli clone` it fails with a cryptic exception.  Given that it's mentioning `str` and `bytes` I suspect this might be a Python 3 conversion oversight.

Using Fedora 35, with `kcli-99.0.0.git.202111160913.0427ae1-1.fc35.x86_64` from COPR.

```
$ kcli list vms
Using local libvirt as no client was specified...
+-----------+--------+-----+---------------------------------------+-------+-----------+
|    Name   | Status | Ips |                 Source                |  Plan |  Profile  |
+-----------+--------+-----+---------------------------------------+-------+-----------+
|  cluster3 |  down  |     | Fedora-Cloud-Base-34-1.2.x86_64.qcow2 | kvirt |  default  |
| kata_base |  down  |     | Fedora-Cloud-Base-34-1.2.x86_64.qcow2 | kvirt | kata_vfio |
+-----------+--------+-----+---------------------------------------+-------+-----------+
$ kcli clone -b kata_base kata_clone
Cloning vm kata_clone from vm kata_base...
Using local libvirt as no client was specified...
Traceback (most recent call last):
  File "/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.10/site-packages/kvirt/cli.py", line 4386, in cli
    args.func(args)
  File "/usr/lib/python3.10/site-packages/kvirt/cli.py", line 1262, in clone_vm
    k.clone(base, name, full=full, start=start)
  File "/usr/lib/python3.10/site-packages/kvirt/providers/kvm/__init__.py", line 2014, in clone
    conn.defineXML(newxml)
  File "/usr/lib64/python3.10/site-packages/libvirt.py", line 4405, in defineXML
    ret = libvirtmod.virDomainDefineXML(self._o, xml)
TypeError: virDomainDefineXML() argument 2 must be str or None, not bytes
```

Additionally the failed clone leaves behind an unfinished libvirt image:
```
$ virsh vol-list dwg
 Name                                    Path
----------------------------------------------------------------------------------------------------------------
...
 kata_clone_0.img                        /home/dwg/mirror/libvirt-images/kata_clone_0.img
```

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/807d959e476fb29dae266dc1502c4ae04f0c2d3b
(this was a python2 left over actually).
Also incorporated in a posterior commit the last vm logic for cloned one
