### ISSUE TITLE
Cannot delete plans with snapshots

### ISSUE THREAD

**Issue by morenod** [karmab/kcli#37]
kcli fails when trying to delete a plan with a snapshot

$ kcli delete rhel73
Using local hypervisor as no kcli.yml was found...
Do you want to continue? [y/N]: y
Deleted vm rhel73...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 9, in <module>
    load_entry_point('kcli==5.14', 'console_scripts', 'kcli')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1😏, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 188, in delete
    k.delete(name)
  File "/usr/lib/python2.7/site-packages/kvirt/kvm/__init__.py", line 710, in delete
    vm.undefine()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2831, in undefine
    if ret == -1: raise libvirtError ('virDomainUndefine() failed', dom=self)
libvirt.libvirtError: Requested operation is not valid: cannot delete inactive domain with 1 snapshots

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/d2143449c8ba6927778f7f924bf46bc1a8e5928e
with a message indicating vm cant be deleted because of existing snapshots
