### ISSUE TITLE
kcli list vms fails if a domain is stopped AND it has a host usb device passed through

### ISSUE THREAD

**Issue by aussielunix** [karmab/kcli#465]
# Bug

I have a domain(vm) that has a host USB device passed through.  
If I run `kcli list vms` whilst the domain is running then I get a list of domains as expected.
If I run `kcli list vms` whilst the domain is in state `shut off` then kcli crashes.

I don't know Python but I think this is where the [issue](https://github.com/karmab/kcli/blob/master/kvirt/providers/kvm/__init__.py#L1739-L1741) is.  

```bash
[~/bin/kcli]
lunix@lumbergh]  (master) -> git --no-pager reflog 
b6018997 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull: Fast-forward
689a1224 HEAD@{1}: clone: from github.com:karmab/kcli.git


[~/bin/kcli]
lunix@lumbergh]  (master) -> python --version
Python 3.10.6
```

```bash
[~/bin/kcli]
lunix@lumbergh]  (master) -> kcli -C gts list vms
+--------+--------+------------+--------+------+---------+
|  Name  | Status |     Ip     | Source | Plan | Profile |
+--------+--------+------------+--------+------+---------+
|  dns1  |   up   | 10.0.99.11 |        |      |         |
| foobar |  down  |            |        |      |         |
| rospxe |   up   |            |        |      |         |
+--------+--------+------------+--------+------+---------+
[~/bin/kcli]
lunix@lumbergh]  (master) -> 
```

```bash
[~/bin/kcli]
lunix@lumbergh]  (master) -> kcli -C gts list vms
Traceback (most recent call last):
  File "/home/lunix/.local/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli', 'console_scripts', 'kcli')())
  File "/home/lunix/bin/kcli/kvirt/cli.py", line 5066, in cli
    args.func(args)
  File "/home/lunix/bin/kcli/kvirt/cli.py", line 634, in list_vm
    _list = config.k.list()
  File "/home/lunix/bin/kcli/kvirt/providers/kvm/__init__.py", line 1530, in list
    vms.append(self.info(vm.name(), vm=vm))
  File "/home/lunix/bin/kcli/kvirt/providers/kvm/__init__.py", line 1741, in info
    bus, slot, function = address.get('bus'), address.get('slot'), address.get('function')
AttributeError: 'NoneType' object has no attribute 'get'
```

Please let me know what else you may need to debug this.

Mick

**Comment by karmab** [comment]
https://github.com/karmab/kcli/commit/07c18636fd37ade2d0f0104041d4917eb470a1ab should fix it

**Comment by aussielunix** [comment]
> [07c1863](https://github.com/karmab/kcli/commit/07c18636fd37ade2d0f0104041d4917eb470a1ab) should fix it

Tested and confirmed it is fixed.

Thank you !
