### ISSUE TITLE
Creating a VM with .img disk and expecting a .qcow2 disk

### ISSUE THREAD

**Issue by kirikae** [karmab/kcli#487]
Unable to to create a RHEL8-based VM.

Steps to reproduce:

1. Install kcli from COPR repo for Fedora 37
2. Run `kcli download image rhel8` and provide the donwload link
3. Configure a profile:
```
cat ~/.kcli/profiles.yml 
rhel8:
  image: rhel-8.7-x86_64-kvm.qcow2
  numcpus: 2
  memory: 4096
  disks:
    - size: 50
  nets:
    - name: default
```
4. Run `kcli create vm -p rhel8 rhel8-vm`

Error output:
```
Deploying vm rhel8-vm from profile rhel8...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kvirt/cli.py", line 4990, in cli
    args.func(args)
  File "/usr/lib/python3.11/site-packages/kvirt/cli.py", line 1377, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kvirt/config.py", line 1016, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kvirt/providers/kvm/__init__.py", line 1295, in create
    storagepool.createXML(volxml, 0)
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 3892, in createXML
    raise libvirtError('virStorageVolCreateXML() failed')
libvirt.libvirtError: internal error: Child process (/usr/bin/qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhel-8.7-x86_64-kvm.qcow2 -o backing_fmt=qcow2,compat=1.1 /var/lib/libvirt/images/rhel8-vm_0.img 52428800K) unexpected exit status 1: qemu-img: /var/lib/libvirt/images/rhel8-vm_0.img: Image is not in qcow2 format
Could not open backing image.
```

It appears that `kcli` is expecting a `.qcow2` disk image file to be present, however it is creating a `.img` disk image file for the VM instead.

Is there a setting that defines the disk image format?

**Comment by karmab** [comment]
I think this just means you used the wrong download link, you should indeed download the qcow2 image from the red hat portal.
the .img suffix is just a convention I use to separate vm disks from the image ones, although most of the times, both are in qcow2 format indeed.

If you want to boot from a rhel iso, you would use iso: in your create vm call ( -P iso=xxx.iso)

**Comment by kirikae** [comment]
Yep, I've goofed and gotten a html file instead of a QCOW image!

Resolved the link to a functioning one and got it all sorted now!
