### ISSUE TITLE
I am unable to run kcli commands on Fedora 37 

### ISSUE THREAD

**Issue by tosin2013** [karmab/kcli#492]
**I installed the kcli with the following steps**
```
sudo dnf -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
sudo systemctl enable --now libvirtd
sudo usermod -aG qemu,libvirt $USER
curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
echo "eval '$(register-python-argcomplete kcli)'" >> ~/.bashrc
```

**Currently installed binaries**
```
$ cat /etc/redhat-release
Fedora release 37 (Thirty Seven)

$ python3 --version
Python 3.11.0
```
**Error Message**
```
$  sudo kcli download image fedora37
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kvirt/cli.py", line 4245, in cli
    delete_subparsers.add_parser('profile', parents=[profiledelete_parser], description=profiledelete_desc,
  File "/usr/lib64/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument : conflicting subparser: profile
```

**Comment by karmab** [comment]
fixed here https://github.com/karmab/kcli/commit/498a8062ffa161418b3a724001b18a4096e2a3ad
thanks for the report and happy new year!
