### ISSUE TITLE
Race condition when retrieving info about deleted vm

### ISSUE THREAD

**Issue by sshnaidm** [karmab/kcli#499]
While installing a cluster I've got an error about non existing domain:

```
---
deployment] **********************************************************
task path: /output/ocp-install.yml:21
fatal: [XXXXXXXXXXX]: FAILED! => {
    "changed": true, 
    "cmd": "kcli create plan --force --paramfile /home/kni/params_cnfdc5.yaml cnfdc5_ci -P tag=4.11 -P version=nightly", 
    "delta": "0:00:00.924175", 
    "end": "2023-01-09 02:51:37.850656", 
    "rc": 1, 
    "start": "2023-01-09 02:51:36.926481"
}

STDERR:

Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==99.0', 'console_scripts', 'kcli')()
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 5126, in cli
    args.func(args)
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 2130, in create_plan
    config.delete_plan(plan, unregister=config.rhnunregister)
  File "/usr/lib/python3.6/site-packages/kvirt/config.py", line 1298, in delete_plan
    for vm in sorted(c.list(), key=lambda x: x['name']):
  File "/usr/lib/python3.6/site-packages/kvirt/providers/kvm/__init__.py", line 1547, in list
    vms.append(self.info(vm.name(), vm=vm))
  File "/usr/lib/python3.6/site-packages/kvirt/providers/kvm/__init__.py", line 1744, in info
    if vm.isActive() and ifaces:
  File "/usr/lib64/python3.6/site-packages/libvirt.py", line 1709, in isActive
    raise libvirtError('virDomainIsActive() failed')
libvirt.libvirtError: Domain not found: no domain with matching uuid 'e81bcb63-8e1e-4ad7-9fe5-3ccd2dec898e' (cnfdb1-master-2)


MSG:

non-zero return code
```

The cluster that should be installed is `cnfdc5_ci`, but domain that was not found is `cnfdb1-master-2` from a different cluster which was exactly being deleted. There is a race condition when calling `vm.isActive` on host which was deleted right now.
```
 kcli version
version: 99.0 commit: 7dd832c 2022/10/19 Available Updates: N/A
```
But this code is still there.

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/0469d9c96959fa5125b8217b5358e114409842c2
