### ISSUE TITLE
[GCP Provider] Usage of a Shared VPC on GCP. Reflect network and subnet to be used.

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#543]
So I'm getting this error when using `KCLI` version __version: 99.0 commit: 708952e 2023/05/15 Available Updates: False__

```text
<-------------> Checking whether the remote cluster - gcp-test - is already deployed <-------------> 
The remote gcp-test cluster is currently NOT deployed, continuing!
<-------------> Creating VM's & deploying K3s on the following client --- <------------->
Deleting loadbalancer api.gcp-test
Using keepalived virtual_router_id 120
Deploying Images...
Image ubuntu-minimal-2204-lts skipped!
Deploying Vms...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 5112, in cli
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1906, in create_k3s_kube
    create_kube(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1882, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 2755, in create_kube
    result = self.create_kube_k3s(cluster, overrides=overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 2782, in create_kube_k3s
    return k3s.create(self, plandir, cluster, overrides)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cluster/k3s/__init__.py", line 156, in create
    result = config.plan(plan, inputfile=f'{plandir}/bootstrap.yml', overrides=bootstrap_overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 2203, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 1051, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/providers/gcp/__init__.py", line 141, in create
    subnets = self.list_subnets()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/providers/gcp/__init__.py", line 878, in list_subnets
    subnets_data = conn.subnetworks().list(region=region, project=project).execute()['items']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

---

We've been speaking about this over on the `Kubernetes Slack Community`. Thought I might as well create an issue to track this more easily.

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli/commit/708952ef06a90ae890356a09d9c73f61bca8bb98 + your PR
