### ISSUE TITLE
[K3S][GCP] - List cluster logic towards GCP.

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#606]
The scenario is as follows:

* New GCP project
* GKE API is **NOT** enabled

We, as part of deploying a K3s cluster on GCE VM's, control that the cluster is not already deployed. As a precautionary measure.

When this is done we get the following error:

```text
<-------------> Checking whether the remote cluster - CLUSTER_NAME - is already deployed <-------------> 
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Kubernetes Engine API has not been used in project PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=PROJECT_ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.147.95:443 {grpc_message:"Kubernetes Engine API has not been used in project PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=PROJECT_ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", grpc_status:7, created_time:"2023-10-03T10:33:49.4588729+02:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 5359, in cli
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1329, in list_cluster
    kubes = config.list_kubes()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 1337, in list_kubes
    kubes.update(gke.list(self))
                 ^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cluster/gke/__init__.py", line 240, in list
    clusters = client.list_clusters(request=request).clusters
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/cloud/container_v1/services/cluster_manager/client.py", line 561, in list_clusters
    response = rpc(
               ^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Kubernetes Engine API has not been used in project PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=PROJECT_ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [links {
  description: "Google developers console API activation"
  url: "https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=PROJECT_ID"
}
, reason: "SERVICE_DISABLED"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "container.googleapis.com"
}
metadata {
  key: "consumer"
  value: "projects/PROJECT_ID"
}
]
```

---

The reason for being "so cautious" is to avoid a scenario where someone, by mistake, overwrites an already existing cluster. Which would be really bad indeed.

So:

- Is it our logic that's infected?

or

- The assumption that KCLI seems to have when listing clusters. That deployed `Kubernets` clusters on `GCP` are always via `GKE`?

Because. Even if we don't execute `kcli --client CLIENT_NAME list cluster` towards `GCP`. This `KCLI` command would still fail generally if one have **NOT** enabled the `GKE API` on `GCP`.

In my mind `KCLI` should be able to list clusters whether they're deployed on `GCE` or `GKE`. Agree @karmab ?

Thanks

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/9d17fbd9dbfcf1c4f689026a9ec2ef8ea095c82d
