### ISSUE TITLE
kvm: s390x arch support

### ISSUE THREAD

**Issue by liudalibj** [karmab/kcli#621]
When I try to create one k8s cluster base on KVM on one s390x machine, I meet follow issues:

0. Can't install kcli on s390x machine with the install script.
https://github.com/confidential-containers/cloud-api-adaptor/issues/1593#issuecomment-1821250150
Install it from pip3:
```
pip3 install kcli
...
Collecting kcli
  Downloading kcli-99.0.202311211909-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 19.6 MB/s
Requirement already satisfied: libvirt-python>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from kcli) (9.9.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.8/dist-packages (from kcli) (3.9.0)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from kcli) (2.10.1)
Requirement already satisfied: argcomplete in /usr/local/lib/python3.8/dist-packages (from kcli) (3.1.6)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from kcli) (5.3.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prettytable->kcli) (0.2.10)
Installing collected packages: kcli
Successfully installed kcli-99.0.202311211909
```

1. `SATA is not supported with this QEMU binary`
```
kcli create vm -i ubuntu2004
...
Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/kvirt/cli.py", line 5364, in cli
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/kvirt/cli.py", line 1536, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile,
  File "/usr/local/lib/python3.8/dist-packages/kvirt/config.py", line 953, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/local/lib/python3.8/dist-packages/kvirt/providers/kvm/__init__.py", line 1331, in create
    conn.defineXML(vmxml)
  File "/usr/local/lib/python3.8/dist-packages/libvirt.py", line 4368, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: unsupported configuration: SATA is not supported with this QEMU binary
```
the kvm xml file for this vm looks like:
```
<source file='/var/lib/libvirt/images/angry-darwin.ISO'/>
<target dev='hdd' bus='sata'/>
<readonly/></disk><input type='mouse' bus='ps2'/><graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' >
<listen type='address' address='127.0.0.1'/>
```
After replace `<target dev='hdd' bus='sata'/>` with `<target dev='hdd' bus='scsi'/>` the issue is fixed.
2. `ubuntu image only have amd64 arch support`
```
kcli create vm -i ubuntu2004
....
Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/kvirt/cli.py", line 5364, in cli
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/kvirt/cli.py", line 1536, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile,
  File "/usr/local/lib/python3.8/dist-packages/kvirt/config.py", line 953, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/local/lib/python3.8/dist-packages/kvirt/providers/kvm/__init__.py", line 1331, in create
    conn.defineXML(vmxml)
  File "/usr/local/lib/python3.8/dist-packages/libvirt.py", line 4368, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: unsupported configuration: Emulator '/usr/bin/qemu-system-s390x' does not support arch 'x86_64'
```

Fixed with download s390x image by hand
```
kcli download image -u https://cloud-images.ubuntu.com/releases/20.04/release/ubuntu-20.04-server-cloudimg-s390x.img ubuntu2004s390x
```
3. `unsupported machine type 'pc'`
```
kcli create vm -i ubuntu2004s390x
...
starving-telecaster not created because internal error: process exited while connecting to monitor: 2023-11-15T13:06:31.641885Z qemu-system-s390x: -machine pc,accel=kvm,usb=off,dump-guest-core=off: unsupported machine type 'pc'
Use -machine help to list supported machines
```
the kvm xml file for the vm looks like:
```
<os >
<type arch='s390x' machine='pc'>hvm</type>
<boot dev='hd'/><boot dev='cdrom'/><boot dev='network'/><bootmenu enable="yes" timeout="60"/>
</os>
```
Fixed with replace `machine='pc'` to `machine='s390-ccw-virtio'`
4. network is not good.
With above fixes we can create cluster with `[kcli_cluster.sh](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/libvirt/kcli_cluster.sh) create` but the network is not good.
```
./kcli_cluster.sh create
...
Waiting for vm peer-pods-ctlplane-0 to finish customisation
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
...
```
fixed the network issue by update the network-config in cloud-init iso, the netwoker interface name for s390x machine should start with`enc`, eg:
```
ethernets:
  enc1:
    dhcp4: true
version: 2
```
5. After the network issue fixed, the containerd issue is reported:
```
Reading state information...
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
/root/pre.sh: line 22: containerd: command not found
Failed to restart containerd.service: Unit containerd.service not found.
Reading package lists...
Building dependency tree...
```
Fixed by update the pre_ubuntu.sh script, remove the arch info, with correct apt-repository for s390x
```
add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
```
6. Now we can get one s390x cluster with some pods in bad status
```
root@liudali-z-test:~/cloud-api-adaptor/libvirt# kubectl get po -A
NAMESPACE       NAME                                           READY   STATUS                  RESTARTS      AGE
autorules       autoruler-76cdf5f9f6-kn8gd                     0/1     Error                   2 (26s ago)   96s
ingress-nginx   ingress-nginx-admission-create-v7mp5           0/1     Pending                 0             96s
ingress-nginx   ingress-nginx-admission-patch-6qbjb            0/1     Pending                 0             96s
ingress-nginx   ingress-nginx-controller-575f4666fb-s4djb      0/1     Pending                 0             96s
kube-flannel    kube-flannel-ds-8w4fb                          1/1     Running                 0             96s
kube-system     coredns-787d4945fb-4jtm9                       1/1     Running                 0             96s
kube-system     coredns-787d4945fb-drhgn                       1/1     Running                 0             96s
kube-system     etcd-peer-pods-ctlplane-0                      1/1     Running                 0             109s
kube-system     kube-apiserver-peer-pods-ctlplane-0            1/1     Running                 0             109s
kube-system     kube-controller-manager-peer-pods-ctlplane-0   1/1     Running                 0             108s
kube-system     kube-multus-ds-5gj8t                           0/1     Init:CrashLoopBackOff   3 (28s ago)   96s
kube-system     kube-proxy-7q9dv                               1/1     Running                 0             96s
kube-system     kube-scheduler-peer-pods-ctlplane-0            1/1     Running                 0             110s
```
The root cause, `autolabeller` and `multus-cni` image do not have s390x arch support:
```
docker manifest inspect quay.io/karmab/autolabeller:latest
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 2255,
		"digest": "sha256:8eae3e6ea1ac8c5e59033f5fed73d4c565ab048c95c336920c7d30b62e7e372c"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 2798338,
			"digest": "sha256:396c31837116ac290458afcb928f68b6cc1c7bdd6963fc72f52f365a2a89c1b5"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 81837521,
			"digest": "sha256:a469694f9e9967274b12ae184e7668677839c2a624bb9eedf368bc162ddbe7ad"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 9820644,
			"digest": "sha256:2284473d68135413f503c6a076976b5823f34680a863b8c10ff99e6aeb16ffd2"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 1870,
			"digest": "sha256:cce15dc61d4ba27f16c73079f88d87c082fe58158d6acb813a3cf02161ebe94b"
		}
	]
}

docker manifest inspect ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"digest": "sha256:a32290033234190806a2156d9d2a56b7ab5019bcf5b55a900f71ec0343a7b6c3",
		"size": 1944
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"digest": "sha256:d812d0c7c96b7031537ddbf0850bf286a5adf68b055c9bf19b2955cb88df77ea",
			"size": 29149882
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"digest": "sha256:93f1794ddc2346f8b3a230e676ccb823a401993aef4b4c6dad032dc8698b349a",
			"size": 118942186
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"digest": "sha256:c94c65df95a40cc9c3ebb397706de11327a7ef2d26f12e7c523eb5afcaaa0e32",
			"size": 4115
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"digest": "sha256:17d9191a4b63a3ac1237fb3ca5eb9d4bde02859404ea0d24472412c8029d7ad3",
			"size": 21477524
		}
	]
}
```
7. Update the [kcli_cluster.sh](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/libvirt/kcli_cluster.sh) script to disable `autolabeller` and `multus`
```
...
create () {
	kcli create kube generic \
		-P domain="kata.com" \
		-P pool="$LIBVIRT_POOL" \
		-P ctlplanes="$CLUSTER_CONTROL_NODES" \
		-P workers="$CLUSTER_WORKERS" \
		-P network="$LIBVIRT_NETWORK" \
		-P image="$CLUSTER_IMAGE" \
		-P sdn=flannel \
		-P multus=false \
		-P autolabeller=false \
		-P nfs=false \
		-P disk_size="$CLUSTER_DISK_SIZE" \
		-P version="$CLUSTER_VERSION" \
		"$CLUSTER_NAME"
...
``` 

Now with the update script and all above fixes we can get one s390x cluster with all pods are running:
```
root@liudali-z-test:~/cloud-api-adaptor/libvirt# kubectl get nodes
NAME                   STATUS   ROLES           AGE   VERSION
peer-pods-ctlplane-0   Ready    control-plane   44m   v1.26.7
peer-pods-worker-0     Ready    <none>          42m   v1.26.7
root@liudali-z-test:~/cloud-api-adaptor/libvirt# kubectl get po -A
NAMESPACE       NAME                                           READY   STATUS      RESTARTS   AGE
ingress-nginx   ingress-nginx-admission-create-vft6f           0/1     Completed   0          43m
ingress-nginx   ingress-nginx-admission-patch-srngf            0/1     Completed   0          43m
ingress-nginx   ingress-nginx-controller-575f4666fb-h2d9h      1/1     Running     0          43m
kube-flannel    kube-flannel-ds-mrsdj                          1/1     Running     0          42m
kube-flannel    kube-flannel-ds-zmcpj                          1/1     Running     0          43m
kube-system     coredns-787d4945fb-7f5td                       1/1     Running     0          43m
kube-system     coredns-787d4945fb-9rkbv                       1/1     Running     0          43m
kube-system     etcd-peer-pods-ctlplane-0                      1/1     Running     0          44m
kube-system     kube-apiserver-peer-pods-ctlplane-0            1/1     Running     0          44m
kube-system     kube-controller-manager-peer-pods-ctlplane-0   1/1     Running     0          44m
kube-system     kube-proxy-c5nxs                               1/1     Running     0          43m
kube-system     kube-proxy-tv8dp                               1/1     Running     0          42m
kube-system     kube-scheduler-peer-pods-ctlplane-0            1/1     Running     0          44m
root@liudali-z-test:~/cloud-api-adaptor/libvirt#
```

**Comment by karmab** [comment]
thanks for the corresponding PR, I'll add additional archs in the autolabeller image, which I maintain
