### ISSUE TITLE
kweb does not start because it cannot import `microshift` module

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#625]
When I tried to test `kweb` for the first time (at least, in some years), I get this stack trace regardless of what parameters I provide:
```
kweb
Traceback (most recent call last):
  File "/usr/bin/kweb", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kweb')())
  File "/usr/bin/kweb", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/kvirt/web/__init__.py", line 13, in <module>
    from kvirt import microshift
ImportError: cannot import name 'microshift' from 'kvirt' (/usr/lib/python3.9/site-packages/kvirt/__init__.py)
```
The stack trace above is from CentOS Stream 9, but Fedora generates a similar one (only python version changes). In both cases, kcli was installed via RPM.

So not sure if there is some packaging error, I missed installing some requirement (I could not find a reference in the docs) or there is some other problem.

**Comment by palonsoro** [comment]
Thanks, but the fix is incomplete. Opening new issue
