### ISSUE TITLE
reservehost enabled failed

### ISSUE THREAD

**Issue by Gictorbit** [karmab/kcli#627]
when I enable reservehost to `True` on my plan `yml` file, it returns this error after running this command:
```sh
kcli create plan -f kclitestplan.yml testplan
```

```sh
Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/kvirt/cli.py", line 5364, in cli
    args.func(args)
  File "/usr/local/lib/python3.11/site-packages/kvirt/cli.py", line 2062, in create_plan
    result = config.plan(plan, ansible=ansible, url=url, path=path, container=container, inputfile=inputfile,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kvirt/config.py", line 2133, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kvirt/config.py", line 953, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kvirt/providers/kvm/__init__.py", line 1396, in create
    self.reserve_host(name, nets, domain)
  File "/usr/local/lib/python3.11/site-packages/kvirt/providers/kvm/__init__.py", line 2499, in reserve_host
    self._create_host_entry(name, ip, netname, domain)
  File "/usr/local/lib/python3.11/site-packages/kvirt/providers/kvm/__init__.py", line 3747, in _create_host_entry
    for line in open(hostsfile):
                ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etcdir/hosts'

```

**Comment by karmab** [comment]
this comes from a missing volume in the container alias.
The following is needed `-v /etc:/etcdir` for the reservehost functionality to work in container mode.
I've added a mention of this in the doc and made sure to fail when such a dir isnt found in the container
