### ISSUE TITLE
kweb does not start because it cannot import `openshift` module

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#628]
Similar to #625 but with another module:
```
$ kweb
Traceback (most recent call last):
  File "/usr/bin/kweb", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kweb')())
  File "/usr/bin/kweb", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/kvirt/web/__init__.py", line 17, in <module>
    from kvirt import openshift
ImportError: cannot import name 'openshift' from 'kvirt' (/usr/lib/python3.9/site-packages/kvirt/__init__.py)
```

Thanks in advance

**Comment by karmab** [comment]
my bad, added the missing import in https://github.com/karmab/kcli/commit/c769811a3a23464b70f15663adbb74a333f5aea7
