### ISSUE TITLE
kcli plan fails to create plan: No such file or directory

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#66]
kcli plan -f ocp-lab-36.yml
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==9.3', 'console_scripts', 'kcli')()
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 1145, in cli
    args.func(args)
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 628, in plan
    config.plan(plan, ansible=ansible, get=get, path=path, autostart=autostart, container=container, noautostart=noautostart, inputfile=inputfile, start=start, stop=stop, delete=delete, delay=delay, topologyfile=topologyfile, scale=scale)
  File "/usr/lib/python2.7/site-packages/kvirt/config.py", line 861, in plan
    common.lastvm(name)
  File "/usr/lib/python2.7/site-packages/kvirt/common/__init__.py", line 260, in lastvm
    for line in fileinput.input("%s/vm" % configdir, inplace=True):
  File "/usr/lib64/python2.7/fileinput.py", line 237, in next
    line = self._readline()
  File "/usr/lib64/python2.7/fileinput.py", line 316, in _readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 2] No such file or directory

kcli looks for the file ~/.kcli/vm, but It doesn't exist.

Meanwhile, the work-around is "touch ~/.kcli/vm"

**Comment by karmab** [comment]
fixed way long time ago!
note that this file is used in order to run kcli ssh without specifying the vm. the last one created in the corresponding provider will be used
