### ISSUE TITLE
kcli create fails with an undefined variable error when `arch` is specified

### ISSUE THREAD

**Issue by yoheiueda** [karmab/kcli#693]
kcli create fails with an undefined variable error when `arch` is specified

```
$ kcli create kube generic -P domain=kata.com -P pool=default -P ctlplanes=1 -P workers=1 -P network=default -P image=ubuntu2204 -P sdn=flannel -P nfs=false -P disk_size=20 -P version=1.30.0 -P arch=s390x -P multus=false -P autolabeller=false peer-pods
Using 192.168.122.253 as api_ip
Using keepalived virtual_router_id 166
Using version v1.30.0
Deploying Vms...
Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 5410, in cli
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 1897, in create_generic_kube
    create_kube(args)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 1876, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/config.py", line 2692, in create_kube
    result = self.create_kube_generic(cluster, overrides=overrides)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/config.py", line 2717, in create_kube_generic
    return kubeadm.create(self, plandir, cluster, overrides)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cluster/kubeadm/__init__.py", line 219, in create
    result = config.plan(plan, inputfile=f'{plandir}/bootstrap.yml', overrides=data)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/config.py", line 2161, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
  File "/usr/local/lib/python3.10/dist-packages/kvirt/config.py", line 958, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/local/lib/python3.10/dist-packages/kvirt/providers/kvm/__init__.py", line 240, in create
    capabilities = self.get_capabilities(overrides.get('arch'))
  File "/usr/local/lib/python3.10/dist-packages/kvirt/providers/kvm/__init__.py", line 204, in get_capabilities
    if 'vmx' in cpuxml:
UnboundLocalError: local variable 'cpuxml' referenced before assignment
```

The `cpuxml` variable is referenced at Line 205, but defined at Lines 188 and 190 only when `arch` is None.

https://github.com/karmab/kcli/blob/9b56b0cdd5846741b38e4dbe7a56155d761dfe27/kvirt/providers/kvm/__init__.py#L180-L208

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/2babdf6fda2f04a4c1e7a814b89193fdac14f664
thanks for the report
