### ISSUE TITLE
How can I add multiple iso/cdroms for libvirt with kcli?

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#711]
I'm trying to make a windows 10 VM, but to get it to find the disk I need to use the virtio iso which has the drivers as a second ISO/CDROM but I can't figure out how to do it with kcli config...

Here is my win10.yml

```
win10-vm:
 iso: /home/user/Win10_22H2_English_x64v1.iso
 numcpus: 4
 memory: 16096
 disks:
  - size: 100
 nets:
  - name: br0
```

If i use virsh edit win10-vm and add the extra <disk></disk> it works..., but I'd like to do this with kcli

```
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/home/user/kcli_vms/win10-vm_0.img'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/home/user/Win10_22H2_English_x64v1.iso'/>
      <target dev='hdc' bus='sata'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/home/user/virtio-win-0.1.262.iso'/>
      <target dev='hdd' bus='sata'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
.....

```

**Comment by karmab** [comment]
let me add support for isos as an array

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/260a0c179dca93fa45c8c8a0ccfa79ac75e3fb67 by adding an additional keyword `extra_keyword` that you can use to point to your iso (either full path or just the name of the iso)

**Comment by ferni7** [comment]
Thank you sir, it's working, posting plan here in case it helps anyone.

```
win10:
 iso: /home/ubuntu/kcli_vms/Win10_22H2_English_x64v1.iso
 extra_iso: /home/ubuntu/kcli_vms/virtio-win-0.1.262.iso
 numcpus: 2
 memory: 8048
 disks:
  - size: 100
#    interface: sata # Could use sata to avoid needing virtio drivers on install
 nets:
  - name: br0
```

**Comment by ferni7** [comment]
Note that if i try to use this with the disk interface: sata it gives me an error

```
win10-test2:
 iso: /home/ubuntu/kcli_vms/Win10_22H2_English_x64v1.iso
# extra_iso: /home/ubuntu/kcli_vms/virtio-win-0.1.262.iso
 extra_iso: /home/ubuntu/kcli_vms/unattend.iso
 numcpus: 2
 memory: 8048
 disks:
  - size: 100
    interface: sata # Could use sata to avoid needing virtio drivers on install
 nets:
  - name: br0
```
Error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/kvirt/cli.py", line 5538, in cli
    args.func(args)
  File "/opt/homebrew/lib/python3.12/site-packages/kvirt/cli.py", line 2202, in create_plan
    result = config.plan(plan, ansible=ansible, url=url, path=path, container=container, inputfile=inputfile,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/kvirt/config.py", line 2176, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/kvirt/config.py", line 957, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/kvirt/providers/kvm/__init__.py", line 1380, in create
    conn.defineXML(vmxml)
  File "/opt/homebrew/lib/python3.12/site-packages/libvirt.py", line 4559, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: unsupported configuration: Found duplicate drive address for disk with target name 'sda' controller='0' bus='0' target='0' unit='1'
```

**Comment by karmab** [comment]
[this](https://github.com/karmab/kcli/commit/f879d48f55955b1a62e4cfac6e7a394224ccdb02) should cover this error
