### ISSUE TITLE
Failures on KVM when default pool is not in /var/lib/libvirt/images

### ISSUE THREAD

**Issue by Akrog** [karmab/kcli#713]
Using the KVM provider if the default pool is not in `/var/lib/libvirt/images` and the directory doesn't exist then we'll bet the following error:

```
Merging ignition data from existing /home/geguileo/.kcli/clusters/fipscluster/bootstrap.ign for fipscluster-bootstrap
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 5518, in cli
    args.func(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1969, in create_openshift_kube
    create_kube(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1923, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 2664, in create_kube
    result = self.create_kube_openshift(cluster, overrides=overrides)
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 2752, in create_kube_openshift
    return openshift.create(self, plandir, cluster, overrides, dnsconfig=dnsconfig)
  File "/usr/lib/python3.9/site-packages/kvirt/cluster/openshift/__init__.py", line 1635, in create
    result = config.plan(plan, inputfile=f'{plandir}/bootstrap.yml', overrides=overrides)
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 2176, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 957, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/lib/python3.9/site-packages/kvirt/providers/kvm/__init__.py", line 792, in create
    with open(f'{ignitiondir}/{name}.ign', 'w') as ignitionfile:
NotADirectoryError: [Errno 20] Not a directory: '/var/lib/libvirt/images/fipscluster-bootstrap.ign'
```

That's because the code has the path for the images hardcoded.

**Comment by karmab** [comment]
One side note, we use this harcoded path because it has selinux rules in place for qemu user to read there. It's not that relevant anymore because default is to put ignition data in a cdrom (like for cloudinit)
