### ISSUE TITLE
how to use Custom image

### ISSUE THREAD

**Issue by BurlyLuo** [karmab/kcli#719]
if there is one Custom image. is there any solution to spec by kcli?
```
[root@rowan> LabasCode]# kcli list vms 
+---------------------+--------+----+--------+------+---------+
|         Name        | Status | Ip | Source | Plan | Profile |
+---------------------+--------+----+--------+------+---------+
| IPv4_K8S_1_28_2_50G |  down  |    |        |      |         |
|         vpp1        |  down  |    |        |      |         |
+---------------------+--------+----+--------+------+---------+
[root@rowan> LabasCode]# 
```
Like IPv4_K8S_1_28_2_50G. qcow2 which is create by virt-install.

**Comment by karmab** [comment]
As long as your initial has a single disk, you can run 

```
kcli export vm IPv4_K8S_1_28_2_50G
```
and then use the resulting disk

**Comment by BurlyLuo** [comment]
```
[root@rowan> LabasCode]# kcli list vm 
+---------------------+--------+----+--------+------+---------+
|         Name        | Status | Ip | Source | Plan | Profile |
+---------------------+--------+----+--------+------+---------+
| IPv4_K8S_1_28_2_50G |  down  |    |        |      |         |
|         vpp1        |  down  |    |        |      |         |
+---------------------+--------+----+--------+------+---------+
[root@rowan> LabasCode]# kcli export vm IPv4_K8S_1_28_2_50G
Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 5543, in cli
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 1840, in export_vm
    result = k.export(name=name, image=image)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/providers/kvm/__init__.py", line 3790, in export
    oldvm = conn.lookupByName(name)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4893, in lookupByName
    raise libvirtError('virDomainLookupByName() failed')
libvirt.libvirtError: Domain not found: no domain with matching name 'vm'
[root@rowan> LabasCode]# 
[root@rowan> LabasCode]# 

```

**Comment by karmab** [comment]
my bad, I meant
`kcli export IPv4_K8S_1_28_2_50G`

**Comment by BurlyLuo** [comment]
```
[root@rowan> ipv4-ipv6-50G]# kcli list vms
+---------------------+--------+--------------+--------+------+---------+
|         Name        | Status |      Ip      | Source | Plan | Profile |
+---------------------+--------+--------------+--------+------+---------+
| IPv4_K8S_1_28_2_50G |   up   | 192.168.2.55 |        |      |         |
|         vpp1        |  down  |              |        |      |         |
+---------------------+--------+--------------+--------+------+---------+
[root@rowan> ipv4-ipv6-50G]# kcli stop vm IPv4_K8S_1_28_2_50G
Stopping vm IPv4_K8S_1_28_2_50G in local...
IPv4_K8S_1_28_2_50G stopped
[root@rowan> ipv4-ipv6-50G]# kcli export IPv4_K8S_1_28_2_50G

Traceback (most recent call last):
  File "/usr/local/bin/kcli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 5543, in cli
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/cli.py", line 1840, in export_vm
    result = k.export(name=name, image=image)
  File "/usr/local/lib/python3.10/dist-packages/kvirt/providers/kvm/__init__.py", line 3810, in export
    pool.createXMLFrom(newvolumexml, oldvolume, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3877, in createXMLFrom
    raise libvirtError('virStorageVolCreateXMLFrom() failed')
libvirt.libvirtError: internal error: storage volume name 'ipv4-Rocky9.qcow2' already in use.
[root@rowan> ipv4-ipv6-50G]# 
[root@rowan> ipv4-ipv6-50G]# 
```

**Comment by BurlyLuo** [comment]
```
[root@rowan> ~]# kcli create vm -i http://192.168.2.100/Rocky9.qcow2
Using jolly-sperez as name of the vm
jolly-sperez not created because Image http://192.168.2.100/Rocky9.qcow2 not found
[root@rowan> ~]# wget http://192.168.2.100/Rocky9.qcow2
--2024-09-14 11:45:40--  http://192.168.2.100/Rocky9.qcow2
Connecting to 192.168.2.100:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1060962304 (1012M) [application/octet-stream]
Saving to: ‘Rocky9.qcow2’

Rocky9.qcow2                                14%[===========>                                                                          ] 148.26M   106MB/s               ^C
[root@rowan> ~]# 

```

**Comment by karmab** [comment]
sorry for that, you are right, what's supported is to provide an url for the iso

**Comment by karmab** [comment]
added support for that in https://github.com/karmab/kcli/commit/2ad12d0db26bf6011b956820158495d08853630a
