### ISSUE TITLE
More variable/parameter type control confusing. UnboundLocalError: cannot access local variable 'virtual_router_id' where it is not associated with a value

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#729]
I'm getting this error

```text
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 5378, in cli
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1904, in create_k3s_kube
    create_kube(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1868, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 2631, in create_kube
    result = self.create_kube_k3s(cluster, overrides=overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 2690, in create_kube_k3s
    return k3s.create(self, plandir, cluster, overrides)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cluster/k3s/__init__.py", line 223, in create
    installparam['virtual_router_id'] = virtual_router_id
                                        ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'virtual_router_id' where it is not associated with a value
```

This with `storedparameters: true` or `storedparameters: false`. That makes no difference.

Further, if I do `storedparameters: false` and the above error happens then I can't list clusters. I'll get this error.

```text
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 5378, in cli
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 1439, in list_cluster
    kubes = config.list_kubes()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/config.py", line 1318, in list_kubes
    _type = installparam.get('kubetype', _type)
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

and

```text
Are you sure? [y/N]: y
Deleting vm minio-test-ctlplane-0 on nemlig-vsphere
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 5378, in cli
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cli.py", line 392, in delete_vm
    kubetype = installparam.get('kubetype', 'generic')
               ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

When trying to delete a deployed VM that was part of a deploy that failed because of the `File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cluster/k3s/__init__.py", line 223, in create installparam['virtual_router_id'] = virtual_router_id` error.

---

1. Deleting the clusters `KCLI parameter file` with `rm -rf ~/.kcli/clusters/minio-test/` and I can list clusters again and delete the dangling VM.

---

Now I'm debugging why the `virtual_router_id` key is not declared .... and I find:

![image](https://github.com/user-attachments/assets/cdb4fb99-147c-46ea-a61b-36cbd3f36f26)

So:

- So __if__ `data.get('virtual_router_id')` is **NOT** `None` then `virtual_router_id` will never be set
- making

![image](https://github.com/user-attachments/assets/5e163ba5-dd33-435d-9167-c5fe94392d83)

Fail.

---

Trying to fix with: https://github.com/karmab/kcli/pull/730

**Comment by karmab** [comment]
I believe https://github.com/karmab/kcli/commit/b9b64b5b62d5a713a6f88d50e50ce93b28473009 should address this

**Comment by larssb** [comment]
Hmm yes .. so let me see if I understand it.

Because `installparam['virtual_router_id']  = data['virtual_router_id']` is now used ( at https://github.com/karmab/kcli/commit/b9b64b5b62d5a713a6f88d50e50ce93b28473009#diff-beb274eff15e5c3934ea8a6e455b5b002449a307f75ef1a29d3580cf42052f05R224 ) ... `virtual_router_id` will have the correct value if `storedparameters` is set to `true` or is not set ( as it defaults to `true` ).

And then if I decide to "do": `storedparameters = false` in a clusters `KCLI parameter file` no `installparam Array` will be declared which can also be beneficial at times.

Correct? Thank you.

**Comment by karmab** [comment]
yes, if you set storedparameters to false, the backup of parameter file wont happen (sothe installparam stuff wont be parsed)
