### ISSUE TITLE
'vim.Folder' object has no attribute 'datastore'

### ISSUE THREAD

**Issue by kundeng** [karmab/kcli#736]
Getting this error when trying to create a VM in vsphere.  It seems that  a folder with the name of the image is created under the root of the datastore, and files are uploaded there,  but then it errors out. 

```
[xxx@myalma devm]$ kcli -C myvsphere create vm -i ubuntu2204 vm1
Image ubuntu2204 not found. Downloading
Grabbing image ubuntu2204 from url https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img
Downloading locally ubuntu-22.04-server-cloudimg-amd64.img
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  623M  100  623M    0     0  9660k      0  0:01:06  0:01:06 --:--:-- 9639k
Converting qcow2 file to vmdk
Using esxi host 192.168.1.94 for import
Uploading /tmp/ubuntu-22.04-server-cloudvmdk-amd64.vmdk to https://192.168.1.94/nfc/5239c71a-7c5b-049c-f42e-0014a74cffb0/disk-0.vmdk
Image ubuntu2204 Added
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 5378, in cli
    args.func(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1610, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile,
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 986, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/lib/python3.9/site-packages/kvirt/providers/vsphere/__init__.py", line 195, in create
    datastores = self._datastores_datacenters()
  File "/usr/lib/python3.9/site-packages/kvirt/providers/vsphere/__init__.py", line 1807, in _datastores_datacenters
    for datastore in clu.datastore:
AttributeError: 'vim.Folder' object has no attribute 'datastore'
```

**Comment by karmab** [comment]
[this](https://github.com/karmab/kcli/commit/1e9bbcb47fac6da2c39efb8aaaa92181c111eb6f) should address it
