### ISSUE TITLE
'Kvirt' object has no attribute 'type'

### ISSUE THREAD

**Issue by easternnl** [karmab/kcli#741]
With the latest build (kcli-99.0.0.git.202411181120.30edffa-0.el9) I got this error:

```
kcli create kube openshift --paramfile shift413-singlenode.yml $cluster
Deploying on client local
Deploying cluster shift413
Using stable version
Using 192.168.122.253 as api_ip
Using existing openshift-install found in your PATH
Using installer version 4.13.53
Using image rhcos-413.92.202402131523-0-openstack.x86_64.qcow2
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 5378, in cli
    args.func(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1914, in create_openshift_kube
    create_kube(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1868, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 2633, in create_kube
    result = self.create_kube_openshift(cluster, overrides)
  File "/usr/lib/python3.9/site-packages/kvirt/config.py", line 2721, in create_kube_openshift
    return openshift.create(self, plandir, cluster, overrides, dnsconfig=dnsconfig)
  File "/usr/lib/python3.9/site-packages/kvirt/cluster/openshift/__init__.py", line 1073, in create
    vmrules = [] if config.k.type == 'kvm' else overrides.get('vmrules', [])
AttributeError: 'Kvirt' object has no attribute 'type'
```

Work around for now is to use one of the previous builds (kcli-99.0.0.git.202411131209.26facb1-0.el9).

The host system is a KVM based on CentOS 9 Stream and completely updated.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/d8095ed8cb5b31e4774b307588d6753149635e7e my bad :)
