### ISSUE TITLE
proxmox: cannot Mb disks

### ISSUE THREAD

**Issue by easternnl** [karmab/kcli#755]
![image](https://github.com/user-attachments/assets/0d01b01a-5c6d-4a92-8d5d-7159a85e90ef)

`(kcli-latest) erik@ERIK-AIRM2 microceph % kcli create plan -f microceph.plan
Using magic-productionready as name of the plan
Deploying Plans...
Missing Url/File for plan mymicroceph. Not creating it...
Deploying Vms...
Traceback (most recent call last):
  File "/Users/erik/venv/kcli-latest/bin/kcli", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/cli.py", line 5385, in cli
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/cli.py", line 2149, in create_plan
    result = config.plan(plan, ansible=ansible, url=url, path=path, container=container, inputfile=inputfile,
                         overrides=overrides, threaded=threaded)
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/config.py", line 2142, in plan
    result = self.create_vm(name, profilename, overrides=currentoverrides, customprofile=profile, k=z,
                            plan=plan, basedir=currentplandir, client=vmclient, onfly=onfly,
                            onlyassets=onlyassets)
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/config.py", line 998, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
                      cpumodel=cpumodel, cpuflags=cpuflags, cpupinning=cpupinning, numamode=numamode, numa=numa,
    ...<8 lines>...
                      cpuhotplug=cpuhotplug, memoryhotplug=memoryhotplug, pcidevices=pcidevices, tpm=tpm, rng=rng,
                      metadata=metadata, securitygroups=securitygroups, vmuser=vmuser, guestagent=guestagent)
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/providers/proxmox/__init__.py", line 590, in create
    initial_disks = self._get_current_disks(new_vm.config.get())
  File "/Users/erik/venv/kcli-latest/src/kcli/kvirt/providers/proxmox/__init__.py", line 1061, in _get_current_disks
    disksize = int(disksize.replace('G', ''))
ValueError: invalid literal for int() with base 10: '3584M'
(kcli-latest) erik@ERIK-AIRM2 microceph %`

Cannot handle a disk in M instead of G size.

**Comment by karmab** [comment]
addressed by https://github.com/karmab/kcli/commit/49ccc4d4ba582eb067c7c67abbb4fa0ae3efe275
