### ISSUE TITLE
float error on 202412211611

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#763]
With 20241219, I can deploy an openshift cluster just fine:

```
[raistlin@daltigoth ~/World/Vincent/Code/GIT/krynn-kcli]$ rpm -q kcli
kcli-99.0.0.git.202412192334.851cbc1-0.el8.x86_64

```
```
[raistlin@daltigoth ~/World/Vincent/Code/GIT/krynn-kcli]$ ./ocp_install.sh
Identity added: /export/home/raistlin/World/Vincent/Code/GIT/krynn-ansible/files/ssh/krynn_rsa (/export/home/raistlin/World/Vincent/Code/GIT/krynn-ansible/files/ssh/krynn_rsa)
(II) Using host daltigoth ...
Deploying on client daltigoth
Deploying cluster ocp4d
Using stable version
Using existing openshift-install found in your PATH
Setting OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE to registry.lasthome.solace.krynn:5000/openshift/release-images:4.16.25-x86_64
Using installer version 4.16.25
Using image rhcos-416.94.202410211619-0-openstack.x86_64.qcow2
WARNING imageContentSources is deprecated, please use ImageDigestSources
INFO Consuming Install Config from target directory
INFO Manifests created in: /export/home/raistlin/.kcli/clusters/ocp4d/manifests and /export/home/raistlin/.kcli/clusters/ocp4d/openshift
Injecting manifest /export/home/raistlin/World/Vincent/Code/GIT/krynn-kcli/extra_manifests/image-content-source-registry-krynn.yaml
Injecting manifest /export/home/raistlin/World/Vincent/Code/GIT/krynn-kcli/extra_manifests/99-openshift-nested-virt.yaml
Injecting manifest /export/home/raistlin/World/Vincent/Code/GIT/krynn-kcli/extra_manifests/99-openshift-infra-udev.yaml
Injecting manifest /export/home/raistlin/World/Vincent/Code/GIT/krynn-kcli/extra_manifests/cluster-network-03-config.yml
Injecting manifest /export/home/raistlin/World/Vincent/Code/GIT/krynn-kcli/extra_manifests/99-worker-enable-iscsid.yaml
WARNING Found override for release image (registry.lasthome.solace.krynn:5000/openshift/release-images:4.16.25-x86_64). Please be warned, this is not advised
INFO Consuming Master Machines from target directory
INFO Consuming OpenShift Install (Manifests) from target directory
INFO Consuming Openshift Manifests from target directory
INFO Consuming Common Manifests from target directory
INFO Consuming Worker Machines from target directory
INFO Ignition-Configs created in: /export/home/raistlin/.kcli/clusters/ocp4d and /export/home/raistlin/.kcli/clusters/ocp4d/auth
Using keepalived virtual_router_id 11
Using 192.168.246.251 for api vip....
Ignoring /etc/hosts
Deploying bootstrap
Deploying Vms...
Merging ignition data from existing /export/home/raistlin/.kcli/clusters/ocp4d/bootstrap.ign for ocp4d-bootstrap
Adding a reserved ip entry for ip 192.168.246.10 and mac 52:54:00:f4:e1:f9
[...]
```

With the latest version, I get a float error:

```
[raistlin@daltigoth ~/World/Vincent/Code/GIT/krynn-kcli]$ rpm -q kcli
kcli-99.0.0.git.202412211611.d530e8c-0.el8.x86_64
```

```
[raistlin@daltigoth ~/World/Vincent/Code/GIT/krynn-kcli]$ ./ocp_install.sh
Identity added: /export/home/raistlin/World/Vincent/Code/GIT/krynn-ansible/files/ssh/krynn_rsa (/export/home/raistlin/World/Vincent/Code/GIT/krynn-ansible/files/ssh/krynn_rsa)
(II) Using host daltigoth ...
Deploying on client daltigoth
Deploying cluster ocp4d
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==99.0', 'console_scripts', 'kcli')()
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 5385, in cli
    args.func(args)
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 1916, in create_openshift_kube
    create_kube(args)
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 1870, in create_kube
    result = config.create_kube(cluster, kubetype, overrides=overrides)
  File "/usr/lib/python3.6/site-packages/kvirt/config.py", line 2635, in create_kube
    result = self.create_kube_openshift(cluster, overrides)
  File "/usr/lib/python3.6/site-packages/kvirt/config.py", line 2692, in create_kube_openshift
    return openshift.create(self, plandir, cluster, overrides, dnsconfig=dnsconfig)
  File "/usr/lib/python3.6/site-packages/kvirt/cluster/openshift/__init__.py", line 847, in create
    elif float(tag) > float(OPENSHIFT_TAG):
ValueError: could not convert string to float: '4.16.25'

```

the command line used is:

`+ kcli -C daltigoth create kube openshift --paramfile ocp4d.yaml --force
`

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli/commit/dff2fd41dc570f49096c4eeff64bf58d61e924d9
